baseurl = "https://danggrianto.github.io/blog"
title = "Automate All Things!"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Code released under the Apache 2.0 license."
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[author]
  name = "Daniel Anggrianto"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Daily Life Of Automation Engineer"
  Author = "Daniel Anggrianto"
  email = "daniel@anggrianto.com"
  Ganalytics = "XX-00000000-0"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/danggrianto"
[[params.social]]
  title = "github"
  url = "https://github.com/danggrianto"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/daniel.andy.ang"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
